socks-port: 7891
redir-port: 7892
tproxy-port: 7893
mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: '127.0.0.1:9090'
secret: ''
routing-mark: 6666
hosts:
  dl.google.com: 180.163.151.161
  dl.l.google.com: 180.163.151.161
  update.googleapis.com: 180.163.151.161
dns:
  enable: true
  listen: '0.0.0.0:53'
  ipv6: false
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
proxies:
  - name: "azure"
    type: ssr
    server: # æœåŠ¡å™¨IP
    port: 7899 # ç«¯å£
    cipher: chacha20-ietf # åè®®
    password: "" #å¯†ç 
    obfs: plain
    protocol: origin
    udp: true
proxy-groups:
  -
    name: 'ğŸŒ å›½å¤–æµé‡'
    type: select
    proxies:
      - 'â™»ï¸ æ•…éšœåˆ‡æ¢'
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'azure'
  -
    name: 'ğŸš¥ å…¶ä»–æµé‡'
    type: select
    proxies:
      - 'ğŸŒ å›½å¤–æµé‡'
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
  -
    name: 'â™»ï¸ æ•…éšœåˆ‡æ¢'
    type: fallback
    proxies:
      - 'azure'
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  -
    name: 'ğŸ¬ å›½é™…æµåª’ä½“'
    type: select
    proxies:
      - 'ğŸŒ å›½å¤–æµé‡'
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'azure'
  -
    name: 'ğŸ¬ å¤§é™†æµåª’ä½“å›½é™…ç‰ˆ'
    type: select
    proxies:
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'ğŸŒ å›½å¤–æµé‡'
      - 'azure'
  -
    name: 'ğŸ® Steam'
    type: select
    proxies:
      - 'ğŸŒ å›½å¤–æµé‡'
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'azure'
  -
    name: 'ğŸŒ å›½é™…ç½‘ç«™'
    type: select
    proxies:
      - 'ğŸŒ å›½å¤–æµé‡'
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'azure'
  -
    name: 'ğŸ  å¤§é™†æµé‡'
    type: select
    proxies:
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'ğŸŒ å›½å¤–æµé‡'
      - 'azure'
  -
    name: 'ğŸ¬ å¤§é™†æµåª’ä½“'
    type: select
    proxies:
      - 'ğŸ  å¤§é™†æµé‡'
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'azure'
  -
    name: 'ğŸ  å¤§é™†ç½‘ç«™'
    type: select
    proxies:
      - 'ğŸ  å¤§é™†æµé‡'
      - 'â¡ï¸ ç›´æ¥è¿æ¥'
      - 'azure'
  -
    name: 'â¡ï¸ ç›´æ¥è¿æ¥'
    type: select
    proxies:
      - DIRECT


rules:
  # > Google
  - DOMAIN-SUFFIX,blog.google,ğŸŒ å›½é™…ç½‘ç«™
  # - DOMAIN-SUFFIX,googletraveladservices.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,clientservices.googleapis.com,ğŸŒ å›½é™…ç½‘ç«™
  # - DOMAIN,dl.google.com,ğŸŒ å›½é™…ç½‘ç«™
  # - DOMAIN,dl.l.google.com,ğŸŒ å›½é™…ç½‘ç«™
  # - DOMAIN,update.googleapis.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,translate.googleapis.com,ğŸŒ å›½é™…ç½‘ç«™
  # >> Google Fonts API
  - DOMAIN,fonts.googleapis.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,fonts.gstatic.com,ğŸŒ å›½é™…ç½‘ç«™
  # >> Firebase Cloud Messaging
  - DOMAIN,mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt1-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt2-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt3-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt4-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt5-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt6-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt7-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  - DOMAIN,alt8-mtalk.google.com,ğŸŒ å›½é™…ç½‘ç«™
  # >> Paramount+
  # - DOMAIN,pubads.g.doubleclick.net,ğŸŒ å›½é™…ç½‘ç«™

  # Unbreak
  - RULE-SET,Unbreak,DIRECT

  # Global Area Network

  # (Streaming Media)
  - RULE-SET,Streaming,ğŸ¬ å›½é™…æµåª’ä½“

  # (StreamingSE)
  - RULE-SET,StreamingSE,ğŸ¬ å¤§é™†æµåª’ä½“å›½é™…ç‰ˆ

  # (Steam)
  - RULE-SET,Steam,ğŸ® Steam

  # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
  - RULE-SET,Global,ğŸŒ å›½é™…ç½‘ç«™

  # (StreamingCN)
  - RULE-SET,StreamingCN,ğŸ¬ å¤§é™†æµåª’ä½“

  # China Area Network
  - RULE-SET,China,ğŸ  å¤§é™†ç½‘ç«™

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT

  # ï¼ˆå¯é€‰ï¼‰ä½¿ç”¨æ¥è‡ª ipipdotnet çš„ ChinaIP ä»¥è§£å†³æ•°æ®ä¸å‡†ç¡®çš„é—®é¢˜ï¼Œä½¿ç”¨ ChinaIP.yaml æ—¶å¯ç¦ç”¨ä¸‹åˆ—ç›´è‡³ï¼ˆåŒ…æ‹¬ï¼‰ã€ŒGEOIP,CNã€è§„åˆ™
  - RULE-SET,ChinaIP,ğŸ  å¤§é™†æµé‡
  # Tencent
  # - IP-CIDR,119.28.28.28/32,ğŸ  å¤§é™†æµé‡
  # - IP-CIDR,182.254.116.0/24,ğŸ  å¤§é™†æµé‡
  # GeoIP China
  # - GEOIP,CN,ğŸ  å¤§é™†æµé‡

  - MATCH,ğŸš¥ å…¶ä»–æµé‡

rule-providers:
# name: # Provider åç§°
#   type: http # http æˆ– file
#   behavior: classical # æˆ– ipcidrã€domain
#   path: # æ–‡ä»¶è·¯å¾„
#   url: # åªæœ‰å½“ç±»å‹ä¸º HTTP æ—¶æ‰å¯ç”¨ï¼Œæ‚¨ä¸éœ€è¦åœ¨æœ¬åœ°ç©ºé—´ä¸­åˆ›å»ºæ–°æ–‡ä»¶ã€‚
#   interval: # è‡ªåŠ¨æ›´æ–°é—´éš”ï¼Œä»…åœ¨ç±»å‹ä¸º HTTP æ—¶å¯ç”¨

  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingSE.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400

  StreamingCN:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingCN.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml
    interval: 86400

  Steam:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Game/Steam.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Game/Steam.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    interval: 86400